packages:
  - "services/*"
  - "packages/*"

catalogs:
  default:
    "@types/node": "^20.0.0"
    "@types/express": "^4.17.0"
    "@types/react": "^18.0.0"
    "@types/react-dom": "^18.0.0"
    express: "^4.18.0"
    react: "^18.0.0"
    react-dom: "^18.0.0"
    next: "^14.0.0"
    typescript: "^5.0.0"
    prisma: "^5.0.0"
    "@prisma/client": "^5.0.0"
    fastapi: "^0.104.0"
    pydantic: "^2.0.0"
    uvicorn: "^0.24.0"
